// Curated character DB. Each entry is structured for two consumers:
//   1. The matcher prompt (uses `look` + `vibeTags` to match a photo)
//   2. The image lookup (`imageUrl` override → `wikiQuery` → fallback)
//
// Adding ~95 characters with `look` descriptions also pushes the system
// prompt past Haiku 4.5's 4096-token cache minimum, so the roster caches
// across requests (~10× cheaper after the first call).

export interface Character {
  id: string;
  name: string;
  source: string;
  sourceType:
    | "anime"
    | "cartoon"
    | "movie"
    | "tv"
    | "game"
    | "book"
    | "comic"
    | "bollywood";
  region: "india" | "japan" | "us" | "uk" | "global" | "korea" | "europe";
  /** One-line visual description — used by the matcher and the most useful
   *  thing for accurate matching. Cover hair (color/length/style), face,
   *  signature clothing/accessories, build. */
  look: string;
  /** Vibe / energy keywords — secondary signal for the matcher. */
  vibeTags: string[];
  /** Optional: direct image URL. Use when the character has no Wikipedia
   *  article of their own (so the show's article would just return a banner). */
  imageUrl?: string;
  /** Wikipedia article title for the character-specific page. Prefer the
   *  character's own article (e.g. "Hermione Granger") over the show. */
  wikiQuery?: string;
}

export const CHARACTERS: Character[] = [
  // ─── INDIAN ─────────────────────────────────────────────────────────────
  { id: "chota-bheem", name: "Chota Bheem", source: "Chhota Bheem", sourceType: "cartoon", region: "india",
    look: "warm brown-skinned Indian boy, round face, big black eyes, short black hair, orange dhoti and white shirt, sturdy build",
    vibeTags: ["strong", "kind", "energetic", "snack-loving", "young hero"],
    wikiQuery: "Chhota Bheem",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/c/c0/Chhota_Bheem_character.png" },
  { id: "mighty-raju", name: "Mighty Raju", source: "Mighty Raju", sourceType: "cartoon", region: "india",
    look: "small Indian kid with spiky black hair, bright eyes, red t-shirt and shorts, energetic posture",
    vibeTags: ["small", "brave", "spunky", "kid superhero"],
    wikiQuery: "Mighty Raju" },
  { id: "krishna-cartoon", name: "Krishna", source: "Krishna Balram", sourceType: "cartoon", region: "india",
    look: "blue-skinned boy with curly black hair, peacock feather crown, yellow dhoti, flute in hand, playful smile",
    vibeTags: ["mischievous", "playful", "divine kid", "flute-carrying"],
    wikiQuery: "Krishna Balram" },
  { id: "hanuman-cartoon", name: "Bal Hanuman", source: "Bal Hanuman", sourceType: "cartoon", region: "india",
    look: "monkey-faced young boy with golden fur, big eyes, red loincloth, muscular small frame",
    vibeTags: ["strong", "loyal", "earnest", "warrior kid"],
    wikiQuery: "Bal Hanuman" },
  { id: "motu", name: "Motu", source: "Motu Patlu", sourceType: "cartoon", region: "india",
    look: "very round bald Indian man, big moustache, red kurta, always grinning, samosa in hand",
    vibeTags: ["round", "samosa-loving", "cheerful", "moustached"],
    wikiQuery: "Motu Patlu" },
  { id: "patlu", name: "Patlu", source: "Motu Patlu", sourceType: "cartoon", region: "india",
    look: "very thin tall Indian man with round glasses, bald, green kurta, calm posture",
    vibeTags: ["thin", "bespectacled", "brainy", "calm"],
    wikiQuery: "Motu Patlu" },
  { id: "shinchan", name: "Shinchan Nohara", source: "Crayon Shin-chan", sourceType: "anime", region: "japan",
    look: "round-faced 5-year-old with thick black bowl-cut hair, tiny eyebrows, big toothy grin, red shirt and yellow shorts",
    vibeTags: ["mischievous", "cheeky", "wild kid"],
    wikiQuery: "Crayon Shin-chan" },
  { id: "nobita", name: "Nobita Nobi", source: "Doraemon", sourceType: "anime", region: "japan",
    look: "skinny boy with round glasses, short black hair, yellow t-shirt over white shirt, blue shorts, soft worried face",
    vibeTags: ["clumsy", "bespectacled", "dreamy", "underdog"],
    wikiQuery: "Nobita Nobi" },
  { id: "geet", name: "Geet", source: "Jab We Met", sourceType: "bollywood", region: "india",
    look: "young Punjabi woman with very long dark wavy hair, expressive eyes, bright kurtis or jeans-and-top, huge smile",
    vibeTags: ["bubbly", "talkative", "long-haired", "free-spirit"],
    wikiQuery: "Jab We Met" },
  { id: "munna-bhai", name: "Munna Bhai", source: "Munna Bhai MBBS", sourceType: "bollywood", region: "india",
    look: "burly Indian man with thick moustache, dark messy hair, white shirt or open-collared shirt, warm crinkled eyes",
    vibeTags: ["big-hearted", "warm", "moustached", "moral gangster"],
    wikiQuery: "Munnabhai M.B.B.S." },
  { id: "phunsukh-wangdu", name: "Phunsukh Wangdu (Rancho)", source: "3 Idiots", sourceType: "bollywood", region: "india",
    look: "lean Indian man, longish wavy black hair, stubble, sparkling curious eyes, kurta or open shirt",
    vibeTags: ["brilliant", "curious", "playful", "anti-establishment"],
    wikiQuery: "3 Idiots" },
  { id: "kabir-singh", name: "Kabir Singh", source: "Kabir Singh", sourceType: "bollywood", region: "india",
    look: "tall Indian man, heavy stubble, messy dark hair, brooding eyes, t-shirt or open shirt, intense glare",
    vibeTags: ["intense", "brooding", "stubble", "moody"],
    wikiQuery: "Kabir Singh" },
  { id: "piku", name: "Piku", source: "Piku", sourceType: "bollywood", region: "india",
    look: "modern Indian woman with shoulder-length wavy hair, kurta-and-jeans, glasses sometimes, no-nonsense expression",
    vibeTags: ["independent", "no-nonsense", "kurta-clad"],
    wikiQuery: "Piku" },
  { id: "bhuvan", name: "Bhuvan", source: "Lagaan", sourceType: "bollywood", region: "india",
    look: "tall lean Indian villager, sun-tanned skin, dhoti and kurta, determined stance, dust on face",
    vibeTags: ["villager", "determined", "earthy", "leader"],
    wikiQuery: "Lagaan" },
  { id: "naina", name: "Naina", source: "Yeh Jawaani Hai Deewani", sourceType: "bollywood", region: "india",
    look: "young Indian woman with straight long dark hair pulled back, round black-framed glasses, kurtas, shy quiet face",
    vibeTags: ["studious", "bespectacled", "quiet", "earnest"],
    wikiQuery: "Yeh Jawaani Hai Deewani" },

  // ─── ANIME ──────────────────────────────────────────────────────────────
  { id: "goku", name: "Son Goku", source: "Dragon Ball", sourceType: "anime", region: "japan",
    look: "tall muscular young man, spiky upright black hair, dark eyes, orange martial-arts gi with blue undershirt, big grin",
    vibeTags: ["spiky hair", "happy", "fight-loving", "innocent"],
    wikiQuery: "Goku" },
  { id: "naruto", name: "Naruto Uzumaki", source: "Naruto", sourceType: "anime", region: "japan",
    look: "blond spiky-haired teen, three whisker marks on each cheek, blue eyes, orange and black tracksuit, headband on forehead",
    vibeTags: ["blond spikes", "loud", "determined", "orange-clad"],
    wikiQuery: "Naruto Uzumaki" },
  { id: "sasuke", name: "Sasuke Uchiha", source: "Naruto", sourceType: "anime", region: "japan",
    look: "pale teen with spiky black-blue hair angled forward, dark intense eyes, dark blue shirt, brooding expression",
    vibeTags: ["black hair", "brooding", "edgy", "cool"],
    wikiQuery: "Sasuke Uchiha" },
  { id: "luffy", name: "Monkey D. Luffy", source: "One Piece", sourceType: "anime", region: "japan",
    look: "lean teen with messy black hair, straw hat with red band, scar under left eye, red open vest, wide grin",
    vibeTags: ["straw hat", "carefree", "wide smile", "adventurer"],
    wikiQuery: "Monkey D. Luffy" },
  { id: "levi", name: "Levi Ackerman", source: "Attack on Titan", sourceType: "anime", region: "japan",
    look: "short man with black undercut hair, pale skin, sharp grey eyes, deadpan expression, all-black tactical gear with white cravat",
    vibeTags: ["undercut", "deadpan", "neat", "intense"],
    wikiQuery: "Levi Ackerman" },
  { id: "mikasa", name: "Mikasa Ackerman", source: "Attack on Titan", sourceType: "anime", region: "japan",
    look: "fit teen girl with straight chin-length black hair, almond eyes, red knit scarf, military jacket, stoic face",
    vibeTags: ["black hair", "red scarf", "stoic", "athletic"],
    wikiQuery: "Mikasa Ackerman" },
  { id: "eren", name: "Eren Yeager", source: "Attack on Titan", sourceType: "anime", region: "japan",
    look: "intense teen with messy brown shoulder-length hair, fierce green eyes, military uniform, angry-jawed expression",
    vibeTags: ["brown hair", "green eyes", "intense", "rebel"],
    wikiQuery: "Eren Yeager" },
  { id: "light", name: "Light Yagami", source: "Death Note", sourceType: "anime", region: "japan",
    look: "neat Japanese teen, light brown shaped hair, polished features, dress shirt, calculating expression",
    vibeTags: ["neat hair", "polished", "intelligent", "studious"],
    wikiQuery: "Light Yagami" },
  { id: "lelouch", name: "Lelouch Lamperouge", source: "Code Geass", sourceType: "anime", region: "japan",
    look: "pale lanky teen, short straight black hair with side bangs, sharp violet eyes, schoolboy uniform or noble dress",
    vibeTags: ["pale", "violet eyes", "tactical", "noble"],
    wikiQuery: "Lelouch Lamperouge" },
  { id: "spike", name: "Spike Spiegel", source: "Cowboy Bebop", sourceType: "anime", region: "japan",
    look: "lanky lazy-cool man, messy mint-green-tinted dark hair, mismatched eyes, blue suit jacket loose tie, cigarette",
    vibeTags: ["lanky", "lazy-cool", "messy hair", "bounty hunter"],
    wikiQuery: "Spike Spiegel" },
  { id: "edward-elric", name: "Edward Elric", source: "Fullmetal Alchemist", sourceType: "anime", region: "japan",
    look: "short blond teen with long braid down back, golden eyes, red coat, black leather over white shirt, defiant stance",
    vibeTags: ["short", "blond braid", "fiery", "red coat"],
    wikiQuery: "Edward Elric" },
  { id: "sailor-moon", name: "Usagi (Sailor Moon)", source: "Sailor Moon", sourceType: "anime", region: "japan",
    look: "girl with very long blond hair in twin buns with streamers, blue eyes, sailor uniform with pink and blue skirt, crybaby face",
    vibeTags: ["twin buns", "blond", "magical girl", "crybaby"],
    wikiQuery: "Sailor Moon" },
  { id: "chihiro", name: "Chihiro", source: "Spirited Away", sourceType: "anime", region: "japan",
    look: "10-year-old Japanese girl, dark brown hair in low ponytail, wide brown eyes, pink t-shirt with green stripes, timid stance",
    vibeTags: ["timid", "pink shirt", "ponytail", "wide-eyed"],
    wikiQuery: "Chihiro Ogino" },
  { id: "totoro", name: "Totoro", source: "My Neighbor Totoro", sourceType: "anime", region: "japan",
    look: "enormous round grey forest creature, white belly, huge ears, wide mouth, sleepy round eyes, gentle",
    vibeTags: ["round", "soft", "huge", "gentle"],
    wikiQuery: "Totoro" },
  { id: "howl", name: "Howl", source: "Howl's Moving Castle", sourceType: "anime", region: "japan",
    look: "vain handsome young wizard, long shiny blond hair, blue eyes, flowing dramatic robes with jewel earrings",
    vibeTags: ["vain", "blond", "flamboyant", "dramatic"],
    wikiQuery: "Howl's Moving Castle" },
  { id: "sophie", name: "Sophie Hatter", source: "Howl's Moving Castle", sourceType: "anime", region: "japan",
    look: "quiet young woman with long brown braid, modest blue dress with white apron, kind face, soft posture",
    vibeTags: ["quiet", "long braid", "kind", "humble"],
    wikiQuery: "Howl's Moving Castle" },
  { id: "kiki", name: "Kiki", source: "Kiki's Delivery Service", sourceType: "anime", region: "japan",
    look: "young witch with bobbed black hair, big red bow on top, navy blue dress, red leather shoes, cheerful eyes",
    vibeTags: ["young witch", "red bow", "bobbed hair", "navy-dressed"],
    wikiQuery: "Kiki's Delivery Service" },
  { id: "asuka", name: "Asuka Langley", source: "Neon Genesis Evangelion", sourceType: "anime", region: "japan",
    look: "teen girl with long fiery red-orange hair and two red hair clips, blue eyes, red plug-suit, proud expression",
    vibeTags: ["red hair", "fiery", "proud", "twin clips"],
    wikiQuery: "Asuka Langley Soryu" },
  { id: "rei", name: "Rei Ayanami", source: "Neon Genesis Evangelion", sourceType: "anime", region: "japan",
    look: "pale teen girl with short pale-blue hair, red eyes, expressionless face, white plug-suit or school uniform",
    vibeTags: ["pale", "blue hair", "red eyes", "quiet"],
    wikiQuery: "Rei Ayanami" },
  { id: "sakura-ccs", name: "Sakura Kinomoto", source: "Cardcaptor Sakura", sourceType: "anime", region: "japan",
    look: "cheerful Japanese girl with short auburn hair, green eyes, athletic build, school uniform or magical-girl outfit",
    vibeTags: ["short brown hair", "green eyes", "cheerful", "magical girl"],
    wikiQuery: "Sakura Kinomoto" },
  { id: "yor", name: "Yor Forger", source: "Spy x Family", sourceType: "anime", region: "japan",
    look: "elegant pale woman with very long straight black hair, red eyes, red turtleneck dress with hairband, polite posture",
    vibeTags: ["long black hair", "red eyes", "elegant", "deadly"],
    wikiQuery: "Spy × Family" },

  // ─── WESTERN ANIMATION ──────────────────────────────────────────────────
  { id: "spongebob", name: "SpongeBob SquarePants", source: "SpongeBob SquarePants", sourceType: "cartoon", region: "us",
    look: "yellow square sponge, two big buck teeth, big blue eyes, white shirt with red tie and brown shorts, endlessly grinning",
    vibeTags: ["yellow", "buck teeth", "cheerful", "square"],
    wikiQuery: "SpongeBob SquarePants" },
  { id: "bart", name: "Bart Simpson", source: "The Simpsons", sourceType: "cartoon", region: "us",
    look: "yellow-skinned 10-year-old boy with spiky blond hair sticking up, orange t-shirt and blue shorts, smartass smirk",
    vibeTags: ["spiky hair", "mischievous", "skater", "smartass"],
    wikiQuery: "Bart Simpson" },
  { id: "lisa", name: "Lisa Simpson", source: "The Simpsons", sourceType: "cartoon", region: "us",
    look: "yellow-skinned 8-year-old girl with pointy spiky hair like sun-rays, red beaded necklace, red sleeveless dress, saxophone often",
    vibeTags: ["smart", "earnest", "spiky-rays hair", "saxophone"],
    wikiQuery: "Lisa Simpson" },
  { id: "bluey", name: "Bluey", source: "Bluey", sourceType: "cartoon", region: "global",
    look: "small blue heeler puppy, fluffy blue and white fur, big black eyes, perky ears, always mid-pounce or smiling",
    vibeTags: ["blue heeler pup", "playful", "imaginative", "energetic kid"],
    wikiQuery: "Bluey (2018 TV series)",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/3/30/Bluey_Heeler.png" },
  { id: "joy", name: "Joy", source: "Inside Out", sourceType: "movie", region: "us",
    look: "glowing yellow emotion, blue pixie-cut hair, huge blue eyes, green leaf-shaped dress, always smiling wide",
    vibeTags: ["yellow glow", "blue pixie hair", "huge smile", "optimistic"],
    wikiQuery: "Joy (Inside Out)",
    imageUrl: "https://upload.wikimedia.org/wikipedia/en/0/0d/Joy_%28Inside_Out%29.png" },
  { id: "anger", name: "Anger", source: "Inside Out", sourceType: "movie", region: "us",
    look: "short red emotion, square body, white collared shirt with tie, perpetually scowling, sometimes literally on fire on top",
    vibeTags: ["red", "fiery temper", "small", "sharp suit"],
    wikiQuery: "Inside Out (2015 film)" },
  { id: "sadness", name: "Sadness", source: "Inside Out", sourceType: "movie", region: "us",
    look: "round blue teardrop-shaped emotion, blue bob-cut hair, big round glasses, white sweater, perpetually droopy face",
    vibeTags: ["blue", "bobbed hair", "glasses", "soft droopy"],
    wikiQuery: "Inside Out (2015 film)" },
  { id: "merida", name: "Merida", source: "Brave", sourceType: "movie", region: "us",
    look: "Scottish girl with huge wild red curly hair, pale freckled skin, green eyes, blue medieval dress, bow and arrow",
    vibeTags: ["red curly hair", "fierce", "archer", "freckled"],
    wikiQuery: "Merida (Brave)" },
  { id: "moana", name: "Moana", source: "Moana", sourceType: "movie", region: "us",
    look: "Polynesian teen girl with long wavy dark brown hair, warm tan skin, red-and-tan tropical clothes, strong build",
    vibeTags: ["wavy brown hair", "brave", "ocean-loving", "warm"],
    wikiQuery: "Moana (character)" },
  { id: "elsa", name: "Elsa", source: "Frozen", sourceType: "movie", region: "us",
    look: "pale young woman with long platinum-white French braid over shoulder, ice-blue eyes, sparkling icy blue gown",
    vibeTags: ["platinum braid", "ice-blue", "regal", "introverted"],
    wikiQuery: "Elsa (Frozen)" },
  { id: "rapunzel", name: "Rapunzel", source: "Tangled", sourceType: "movie", region: "us",
    look: "girl with extremely long blond hair down to floor, wide green eyes, pink-purple dress, barefoot, curious face",
    vibeTags: ["very long blond hair", "wide green eyes", "curious", "barefoot"],
    wikiQuery: "Rapunzel (Tangled)" },
  { id: "mulan", name: "Mulan", source: "Mulan", sourceType: "movie", region: "us",
    look: "Chinese young woman with chin-length black hair, soft-featured face, warrior armor or pink hanfu, determined eyes",
    vibeTags: ["determined", "black hair", "brave", "warrior"],
    wikiQuery: "Fa Mulan" },
  { id: "kim-possible", name: "Kim Possible", source: "Kim Possible", sourceType: "cartoon", region: "us",
    look: "athletic teen girl with shoulder-length red-orange hair, green eyes, green crop top and black cargo pants, confident",
    vibeTags: ["red hair", "athletic", "confident", "green-eyed"],
    wikiQuery: "Kim Possible (character)" },
  { id: "ron-stoppable", name: "Ron Stoppable", source: "Kim Possible", sourceType: "cartoon", region: "us",
    look: "lanky teen boy with floppy blond hair, freckles, red sweater over white t-shirt, goofy easygoing grin",
    vibeTags: ["blond floppy hair", "goofy", "loyal", "easygoing"],
    wikiQuery: "Ron Stoppable" },
  { id: "pinkie-pie", name: "Pinkie Pie", source: "My Little Pony", sourceType: "cartoon", region: "us",
    look: "bright pink pony with bouncy puffball pink mane and tail, blue eyes, party-balloon flank symbol, always grinning",
    vibeTags: ["pink", "bouncy curls", "hyper happy", "party-loving"],
    wikiQuery: "Pinkie Pie" },
  { id: "no-face", name: "No-Face", source: "Spirited Away", sourceType: "anime", region: "japan",
    look: "tall translucent black-cloaked spirit with white expressionless mask, dark voids for eyes, ghostly quiet presence",
    vibeTags: ["mask", "tall", "quiet", "lonely"],
    wikiQuery: "No-Face" },

  // ─── LIVE-ACTION TV / MOVIES ────────────────────────────────────────────
  { id: "harry", name: "Harry Potter", source: "Harry Potter", sourceType: "movie", region: "uk",
    look: "skinny young man with messy black hair, round wire-frame glasses, green eyes, lightning-bolt scar on forehead, school robes",
    vibeTags: ["round glasses", "messy black hair", "scar", "earnest"],
    wikiQuery: "Harry Potter (character)" },
  { id: "hermione", name: "Hermione Granger", source: "Harry Potter", sourceType: "movie", region: "uk",
    look: "young woman with bushy chestnut-brown hair, warm brown eyes, school uniform with red-and-gold tie, alert intelligent face",
    vibeTags: ["bushy brown hair", "brainy", "fierce", "studious"],
    wikiQuery: "Hermione Granger" },
  { id: "ron-weasley", name: "Ron Weasley", source: "Harry Potter", sourceType: "movie", region: "uk",
    look: "tall lanky teen boy with bright red hair, freckles, blue eyes, school robes or hand-me-down sweaters, goofy",
    vibeTags: ["red hair", "freckles", "tall", "goofy"],
    wikiQuery: "Ron Weasley" },
  { id: "luna", name: "Luna Lovegood", source: "Harry Potter", sourceType: "movie", region: "uk",
    look: "dreamy girl with very long pale blond hair, wide blue eyes, quirky accessories like radish earrings, ethereal soft expression",
    vibeTags: ["dreamy", "long blond hair", "quirky accessories", "ethereal"],
    wikiQuery: "Luna Lovegood" },
  { id: "eleven", name: "Eleven", source: "Stranger Things", sourceType: "tv", region: "us",
    look: "small girl with very short buzz-cut brown hair (later grown into a curly bob), huge intense brown eyes, pink dress or oversize clothes",
    vibeTags: ["short hair", "quiet intensity", "wide eyes", "soft but powerful"],
    wikiQuery: "Eleven (Stranger Things)" },
  { id: "wednesday", name: "Wednesday Addams", source: "Wednesday", sourceType: "tv", region: "us",
    look: "pale teen girl with two long jet-black braids, deadpan stare, black-and-white school uniform or all-black clothes, sharp face",
    vibeTags: ["black braids", "pale", "deadpan", "gothic"],
    wikiQuery: "Wednesday Addams" },
  { id: "tony-stark", name: "Iron Man (Tony Stark)", source: "Marvel", sourceType: "movie", region: "us",
    look: "fit man with neat dark hair, signature goatee with thin moustache, brown eyes, smart-casual or arc-reactor t-shirt, witty smirk",
    vibeTags: ["goatee", "sharp", "witty", "engineer"],
    wikiQuery: "Iron Man" },
  { id: "cap", name: "Captain America (Steve Rogers)", source: "Marvel", sourceType: "movie", region: "us",
    look: "tall muscular blond man, square jaw, blue eyes, clean-cut hair, red-white-and-blue suit or sober jacket, earnest expression",
    vibeTags: ["blond", "square jaw", "earnest", "muscular"],
    wikiQuery: "Captain America" },
  { id: "thor", name: "Thor", source: "Marvel", sourceType: "movie", region: "us",
    look: "huge muscular blond man with long flowing wavy hair, warm blue eyes, beard, royal Asgardian armor or simple t-shirt",
    vibeTags: ["long blond hair", "muscular", "warm-eyed", "royal"],
    wikiQuery: "Thor (Marvel Cinematic Universe)" },
  { id: "loki", name: "Loki", source: "Marvel", sourceType: "movie", region: "us",
    look: "lean pale man with slicked-back long jet-black hair, green eyes, sly smile, green-and-gold armor or sharp suit",
    vibeTags: ["long black hair", "pale", "sly", "trickster"],
    wikiQuery: "Loki (Marvel Cinematic Universe)" },
  { id: "natasha", name: "Black Widow", source: "Marvel", sourceType: "movie", region: "us",
    look: "fit woman with shoulder-length straight red hair, green eyes, sharp face, tactical black bodysuit, calm deadly expression",
    vibeTags: ["red hair", "athletic", "spy", "calm"],
    wikiQuery: "Black Widow (Natasha Romanoff)" },
  { id: "peter-parker", name: "Spider-Man (Peter Parker)", source: "Marvel", sourceType: "movie", region: "us",
    look: "lanky teen boy with messy brown hair, brown eyes, nerdy t-shirts and hoodies, good-natured face",
    vibeTags: ["brown messy hair", "nerdy", "lanky", "teen"],
    wikiQuery: "Spider-Man" },
  { id: "wonder-woman", name: "Wonder Woman (Diana)", source: "DC", sourceType: "movie", region: "us",
    look: "tall muscular woman with long dark wavy hair, blue eyes, regal expression, red-and-gold armor or simple elegant outfit",
    vibeTags: ["dark wavy hair", "regal", "muscular", "warrior"],
    wikiQuery: "Wonder Woman (2017 film)" },
  { id: "katniss", name: "Katniss Everdeen", source: "The Hunger Games", sourceType: "movie", region: "us",
    look: "lean young woman with very long dark brown hair in a side braid, grey eyes, leather jacket and bow, weary stoic face",
    vibeTags: ["long braid", "fierce", "archer", "stoic"],
    wikiQuery: "Katniss Everdeen" },
  { id: "rey", name: "Rey", source: "Star Wars", sourceType: "movie", region: "us",
    look: "young woman with light brown hair in three small buns down back, freckled face, beige desert robes, holding staff or lightsaber",
    vibeTags: ["triple buns", "scrappy", "scavenger", "earnest"],
    wikiQuery: "Rey (Star Wars)" },
  { id: "padme", name: "Padmé Amidala", source: "Star Wars", sourceType: "movie", region: "us",
    look: "elegant young woman with elaborate dark braided hairstyles, pale skin, ornate flowing gowns or queen's regalia, composed face",
    vibeTags: ["elaborate hairstyles", "regal", "calm", "elegant"],
    wikiQuery: "Padmé Amidala" },
  { id: "leia", name: "Princess Leia", source: "Star Wars", sourceType: "movie", region: "us",
    look: "young woman with brown hair in iconic side buns over each ear, white floor-length robe, commanding posture",
    vibeTags: ["side buns", "white robe", "fierce", "commanding"],
    wikiQuery: "Princess Leia" },
  { id: "indiana", name: "Indiana Jones", source: "Indiana Jones", sourceType: "movie", region: "us",
    look: "rugged man in brown fedora and leather jacket, stubble, white shirt, whip on hip, weathered adventurer's face",
    vibeTags: ["fedora", "leather jacket", "rugged", "adventurer"],
    wikiQuery: "Indiana Jones" },
  { id: "walter-white", name: "Walter White", source: "Breaking Bad", sourceType: "tv", region: "us",
    look: "middle-aged man with shaved bald head, neat dark goatee, round glasses, beige jacket or black porkpie hat, intense glare",
    vibeTags: ["bald", "goatee", "intense", "glasses"],
    wikiQuery: "Walter White (Breaking Bad)" },
  { id: "rachel", name: "Rachel Green", source: "Friends", sourceType: "tv", region: "us",
    look: "young woman with the iconic layered honey-blond Rachel haircut, blue eyes, 90s casual fashion, warm smile",
    vibeTags: ["the rachel cut", "stylish", "warm", "trendy"],
    wikiQuery: "Rachel Green" },
  { id: "phoebe", name: "Phoebe Buffay", source: "Friends", sourceType: "tv", region: "us",
    look: "tall young woman with very long straight pale-blond hair, hazel eyes, bohemian patterned clothes, dreamy spaced-out face",
    vibeTags: ["long blond hair", "free-spirit", "quirky", "musician"],
    wikiQuery: "Phoebe Buffay" },
  { id: "daenerys", name: "Daenerys Targaryen", source: "Game of Thrones", sourceType: "tv", region: "us",
    look: "young woman with very long platinum-white hair often in elaborate braids, pale violet eyes, blue gown or leather riding clothes",
    vibeTags: ["platinum hair", "regal", "violet eyes", "queenly"],
    wikiQuery: "Daenerys Targaryen" },
  { id: "arya", name: "Arya Stark", source: "Game of Thrones", sourceType: "tv", region: "us",
    look: "small teen girl with short scruffy dark brown hair, grey eyes, leather travel clothes, small sword (Needle), fierce face",
    vibeTags: ["short brown hair", "tomboy", "small", "fierce"],
    wikiQuery: "Arya Stark" },

  // ─── GAMES ──────────────────────────────────────────────────────────────
  { id: "mario", name: "Mario", source: "Super Mario", sourceType: "game", region: "japan",
    look: "short stocky Italian plumber with thick black moustache, red cap with M logo, blue overalls over red shirt, cheerful round face",
    vibeTags: ["moustache", "red cap", "round", "cheerful"],
    wikiQuery: "Mario" },
  { id: "peach", name: "Princess Peach", source: "Super Mario", sourceType: "game", region: "japan",
    look: "tall young woman with very long blond hair, blue eyes, pink ballgown with white gloves, gold crown, kind regal smile",
    vibeTags: ["blond", "pink dress", "kind", "regal"],
    wikiQuery: "Princess Peach" },
  { id: "link", name: "Link", source: "The Legend of Zelda", sourceType: "game", region: "japan",
    look: "lean young man with shaggy dirty-blond hair, pointed elf ears, blue eyes, green tunic with cap (or blue Champion's tunic), sword and shield",
    vibeTags: ["green tunic", "blond", "blue eyes", "hero"],
    wikiQuery: "Link (The Legend of Zelda)" },
  { id: "zelda", name: "Princess Zelda", source: "The Legend of Zelda", sourceType: "game", region: "japan",
    look: "elegant young woman with long honey-blond hair, pointed elf ears, blue eyes, regal pink-and-white royal gown",
    vibeTags: ["blond", "elegant", "regal", "pointed ears"],
    wikiQuery: "Princess Zelda" },
  { id: "lara", name: "Lara Croft", source: "Tomb Raider", sourceType: "game", region: "uk",
    look: "athletic young woman with dark brown hair in long braid, tan skin, brown eyes, teal tank top with cargo shorts, dual pistols",
    vibeTags: ["brunette braid", "athletic", "adventurer", "tan"],
    wikiQuery: "Lara Croft" },
  { id: "aloy", name: "Aloy", source: "Horizon Zero Dawn", sourceType: "game", region: "us",
    look: "athletic young woman with bright red-orange hair in tight braids and beads, freckled face, green eyes, tribal leather-and-fur armor",
    vibeTags: ["red braids", "freckled", "fierce", "tribal warrior"],
    wikiQuery: "Aloy" },
  { id: "geralt", name: "Geralt of Rivia", source: "The Witcher", sourceType: "game", region: "europe",
    look: "muscular older man with long white hair pulled back, sharp scarred face, glowing yellow cat-eyes, dark leather armor with twin swords",
    vibeTags: ["white hair", "scars", "gruff", "yellow eyes"],
    wikiQuery: "Geralt of Rivia" },
  { id: "cloud", name: "Cloud Strife", source: "Final Fantasy VII", sourceType: "game", region: "japan",
    look: "lean young man with spiky bright blond hair, intense blue eyes, dark sleeveless turtleneck, huge sword strapped to back, brooding",
    vibeTags: ["blond spiky hair", "blue eyes", "brooding", "huge sword"],
    wikiQuery: "Cloud Strife" },
  { id: "tifa", name: "Tifa Lockhart", source: "Final Fantasy VII", sourceType: "game", region: "japan",
    look: "athletic young woman with very long straight black hair, ruby-red eyes, white tank top with black skirt, gloved fists, warm strong face",
    vibeTags: ["long black hair", "fighter", "white tank", "athletic"],
    wikiQuery: "Tifa Lockhart" },
  { id: "master-chief", name: "Master Chief", source: "Halo", sourceType: "game", region: "us",
    look: "huge soldier in green armored Mjolnir suit, full helmet with golden visor (never removed), towering stoic presence",
    vibeTags: ["green armor", "tall", "stoic", "helmet"],
    wikiQuery: "Master Chief (Halo)" },

  // ─── BOOKS / LITERATURE ─────────────────────────────────────────────────
  { id: "sherlock", name: "Sherlock Holmes", source: "Sherlock Holmes", sourceType: "book", region: "uk",
    look: "lanky English man with sharp-angled face, dark hair, piercing pale eyes, Victorian suit with overcoat, sometimes deerstalker hat and pipe",
    vibeTags: ["sharp", "deerstalker", "lanky", "deductive"],
    wikiQuery: "Sherlock Holmes" },
  { id: "bilbo", name: "Bilbo Baggins", source: "The Hobbit", sourceType: "book", region: "uk",
    look: "short hobbit with curly brown hair on head and on huge bare feet, kind round face, soft middle, weathered green cloak and waistcoat",
    vibeTags: ["short", "curly hair", "cozy", "hobbit feet"],
    wikiQuery: "Bilbo Baggins" },
  { id: "frodo", name: "Frodo Baggins", source: "The Lord of the Rings", sourceType: "book", region: "uk",
    look: "small young hobbit with curly dark hair, very blue eyes, soft face, simple traveling cloak, ring around neck, burdened expression",
    vibeTags: ["small", "blue eyes", "earnest", "soft"],
    wikiQuery: "Frodo Baggins" },
  { id: "aragorn", name: "Aragorn", source: "The Lord of the Rings", sourceType: "book", region: "uk",
    look: "weathered ranger with long unkempt dark hair, dark stubble beard, grey eyes, leather-and-cloak ranger gear, dignified noble bearing",
    vibeTags: ["ranger", "long dark hair", "stubble", "noble"],
    wikiQuery: "Aragorn" },
  { id: "gandalf", name: "Gandalf", source: "The Lord of the Rings", sourceType: "book", region: "uk",
    look: "tall wizard with very long white beard and white hair, pointy grey or white hat, grey or white robes, twinkly bushy-browed eyes, wooden staff",
    vibeTags: ["long white beard", "wise", "tall", "wizard hat"],
    wikiQuery: "Gandalf" },
  { id: "tyrion", name: "Tyrion Lannister", source: "Game of Thrones", sourceType: "book", region: "us",
    look: "dwarf man with shoulder-length light-blond hair, mismatched green-and-black eyes, scarred face, fine medieval clothes, witty smirk",
    vibeTags: ["short", "blond", "witty", "scarred"],
    wikiQuery: "Tyrion Lannister" },
  { id: "matilda", name: "Matilda", source: "Matilda", sourceType: "book", region: "uk",
    look: "small bookish English girl with shoulder-length straight brown hair, often with a red ribbon bow, blue dress, alert serious eyes",
    vibeTags: ["bookish", "bow in hair", "small", "brilliant"],
    wikiQuery: "Matilda (novel)" },
  { id: "atticus", name: "Atticus Finch", source: "To Kill a Mockingbird", sourceType: "book", region: "us",
    look: "middle-aged Southern lawyer in three-piece suit, round wire glasses, neatly combed grey-streaked hair, quietly dignified",
    vibeTags: ["round glasses", "quiet dignity", "lawyer", "soft-spoken"],
    wikiQuery: "Atticus Finch" },
  { id: "holden", name: "Holden Caulfield", source: "The Catcher in the Rye", sourceType: "book", region: "us",
    look: "tall lanky teen boy with messy brown hair, prematurely greying patches, the iconic red hunting cap with earflaps, overcoat, wistful face",
    vibeTags: ["red hunting hat", "moody teen", "tall", "wistful"],
    wikiQuery: "Holden Caulfield" },
  { id: "poirot", name: "Hercule Poirot", source: "Hercule Poirot novels", sourceType: "book", region: "europe",
    look: "small dapper Belgian man with perfectly waxed handlebar moustache, egg-shaped head, neat three-piece suit, fastidious posture",
    vibeTags: ["waxed moustache", "neat", "round", "fastidious"],
    wikiQuery: "Hercule Poirot" },

  // ─── KOREAN / GLOBAL POP ────────────────────────────────────────────────
  { id: "gi-hun", name: "Gi-hun", source: "Squid Game", sourceType: "tv", region: "korea",
    look: "middle-aged Korean man with messy salt-and-pepper hair, weathered weary face, faded green tracksuit with number 456, soft eyes",
    vibeTags: ["green tracksuit", "messy hair", "weathered", "everyman"],
    wikiQuery: "Gi-hun" },
  { id: "sae-byeok", name: "Kang Sae-byeok", source: "Squid Game", sourceType: "tv", region: "korea",
    look: "young Korean woman with short choppy black hair, sharp jaw, intense quiet eyes, green tracksuit with number 067, stoic",
    vibeTags: ["sharp", "short hair", "quiet", "intense"],
    wikiQuery: "Squid Game" },
];

export const CHARACTER_BY_ID: Record<string, Character> = Object.fromEntries(
  CHARACTERS.map((c) => [c.id, c])
);
